### ISSUE TITLE
[Android] Path issue.

### ISSUE THREAD

**Issue by kwanguuuu** [flutter-moum/flutter_screenshot_callback#13]
Depend on mobile device, there are 2(maybe more..) different path for screenshots.

e.g:
/storage/emulated/0/**Pictures**/Screenshots/
/storage/emulated/0/**DCMI**/Screenshots/

So, We  need to check before setting the path which is mobile device has in plug-in 

Maybe..

1. check the device's screenshot path when plug-in use.
2. init both of paths no matter what the device path
3. change the FileObserver to other class

😭

**Comment by kwanguuuu** [comment]
우선경로(/DCMI, /PICTURES)를 바라보는 FileObserver를 각각 만들어 method호출시 실행하도록 하겠음.

**Comment by kwanguuuu** [comment]
API19인 단말기에서 테스트 했을 때, 
플러터 배포 후 실행시점에 에러가 남.. 확인해 봐야할듯.
캡처 실행 종료는 잘됨
에뮬 api19로 설정해서 실행했는데 에뮬이 실행이 안되서 우선 테스트 보류........:(
```
11-08 17:19:54.397 16087-16087/com.flutter.moum.screenshot_callback_example D/dalvikvm: DexOpt: unable to opt direct call 0x00a4 at 0x1c in Lio/flutter/view/FlutterMain;.ensureInitializationCompleteAsync
11-08 17:19:54.397 16087-16087/com.flutter.moum.screenshot_callback_example D/dalvikvm: DexOpt: unable to opt direct call 0x00b7 at 0x02 in Lio/flutter/view/FlutterMain;.initResources
11-08 17:19:54.407 16087-16087/com.flutter.moum.screenshot_callback_example D/dalvikvm: DexOpt: unable to opt direct call 0x00b9 at 0x1e in Lio/flutter/view/FlutterMain;.initResources
11-08 17:19:54.407 16087-16087/com.flutter.moum.screenshot_callback_example D/dalvikvm: DexOpt: unable to opt direct call 0x00a5 at 0x07 in Lio/flutter/view/FlutterMain;.startInitialization
11-08 17:19:54.407 16087-16087/com.flutter.moum.screenshot_callback_example D/AndroidRuntime: Shutting down VM
11-08 17:19:54.407 16087-16087/com.flutter.moum.screenshot_callback_example W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4174cd58)
11-08 17:19:54.407 16087-16087/com.flutter.moum.screenshot_callback_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flutter.moum.screenshot_callback_example, PID: 16087
    java.lang.NoClassDefFoundError: io.flutter.view.FlutterMain$Settings
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:110)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4417)
        at android.app.ActivityThread.access$1500(ActivityThread.java:143)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5090)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
        at dalvik.system.NativeStart.main(Native Method)

```

**Comment by kwanguuuu** [comment]
api 19넘어갈거임 패스

**Comment by songyiYu** [comment]
알아보니 구글 플레이스토어에서 이제 API 28 보다 작으면 앱 올려도 리젝한다고 합니다ㅎㅎ 고로 19는 현 시점으로 아주아주 낮은 버전이기 때문에 충분히 넘어가도 될 사항인것 같아요
