### ISSUE TITLE
stop() on a null object reference ：NullPointerException

### ISSUE THREAD

**Issue by LiuDongCai** [flutter-moum/flutter_screenshot_callback#87]
PlatformException(error, Attempt to invoke virtual method 'void com.flutter.moum.screenshot_callback.ScreenshotDetector.stop()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void com.flutter.moum.screenshot_callback.ScreenshotDetector.stop()' on a null object reference
	at com.flutter.moum.screenshot_callback.ScreenshotCallbackPlugin.onMethodCall(SourceFile:7)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:2)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(SourceFile:2)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(SourceFile:3)
	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
)
![image](https://github.com/flutter-moum/flutter_screenshot_callback/assets/18276939/4e99438f-e0e5-4f7c-887b-1f4838425b3f)

**Comment by LiuDongCai** [comment]
version：
flutter 3.13.9
Dart 3.1.5
screenshot_callback 3.0.1
